/*
 * Reservation List Api
 *
 * Reservation List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xskriba@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package reservation

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type HealthAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // GetHealth - Provides health
   GetHealth(ctx *gin.Context)

 }

 // partial implementation of HealthAPI - all functions must be implemented in add on files
type implHealthAPI struct {

}

func newHealthAPI() HealthAPI {
  return &implHealthAPI{}
}

func (this *implHealthAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodGet, "/health", this.GetHealth)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // GetHealth - Provides health
// func (this *implHealthAPI) GetHealth(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

