/*
 * Reservation Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: xbublavy@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package reservation

type GetAmbulanceReservationsById200Response struct {

	Ambulance Ambulance `json:"ambulance,omitempty"`

	Reservations []Reservation `json:"reservations,omitempty"`
}
