/*
 * Reservation Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: xbublavy@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package reservation

import (
	"time"
)

type RequestExamination200ResponseInner struct {

	Ambulance Ambulance `json:"ambulance,omitempty"`

	TimeSlot time.Time `json:"timeSlot,omitempty"`
}
