/*
 * Reservation Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: xbublavy@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package reservation

import (
	"time"
)

type ReservationInput struct {

	Id string `json:"id,omitempty"`

	AmbulanceId string `json:"ambulanceId"`

	PatientId string `json:"patientId,omitempty"`

	Start time.Time `json:"start"`

	End time.Time `json:"end"`

	ExaminationType MedicalExaminations `json:"examinationType"`

	// Optional message for the reservation
	Message string `json:"message,omitempty"`
}
