/*
 * Reservation Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: xbublavy@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package reservation

type CreateAmbulanceRequest struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Address string `json:"address"`

	OfficeHours OfficeHours `json:"officeHours"`

	MedicalExaminations []MedicalExaminations `json:"medicalExaminations"`
}
