/*
 * Reservation Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: xbublavy@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package reservation

import (
	"time"
)

type Reservation struct {

	Patient Patient `json:"patient"`

	TimeSlot time.Time `json:"timeSlot"`

	// Optional message for the reservation
	Message string `json:"message,omitempty"`
}
