/*
 * Reservation List Api
 *
 * Reservation List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xskriba@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package reservation

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newHealthAPI()
    api.addRoutes(group)
  }
  
}