apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: xskriba-xbublavy-reservation-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: xskriba-xbublavy-reservation-webapi-config
    literals:
      - database=xskriba-xbublavy-reservation
      - collection=reservation
patches:
  - path: patches/webapi.deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: xskriba-xbublavy-reservation-webapi
