kind: Service
apiVersion: v1
metadata:
  name: xskriba-xbublavy-reservation-webapi
spec:
  selector:
    pod: xskriba-xbublavy-reservation-webapi-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: webapi-port
